# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.6.1

    #working_directory: ~/projects/webapp-flask/

    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t "$DOCKER_IMAGE_NAME".  # Build the docker image 
      - run: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin    
      - run: docker push "$DOCKER_IMAGE_NAME":latestsample # push the docker image to hub
      - run: docker run -d -p 5000:5000 DOCKER_IMAGE_NAME:latestsample hellopythonworld app.py
      - run: curl http://localhost:5000
